version: '3.9'
services:  
  userservice:
    build:
      context: ./authentication_service
    container_name: authentication_service_ct
    ports:
      - "5000:5000"
  secure_deliveryservice:
    build:
      context: ./Resful-API
    container_name: secured_restful_api_ct
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5001:5000"